services:
  mongo:
    image: mongo:6.0
    container_name: moniflow-mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  collector:
    build: ./services/metrics_collector
    volumes:
      - ./services/metrics_collector:/app
    env_file:
      - .env
    ports:
      - "8001:8001"
  
  alert_service:
    build: ./services/alert_service
    ports:
      - "8002:8002"

  dashboard_service:
    build: ./services/dashboard_service
    ports:
      - "8003:8003"

  user_management:
    build: ./services/user_management
    volumes:
      - ./services/user_management:/app
    depends_on:
      - mongo
    environment:
      MONGO_URI: "mongodb://admin:password@mongo:27017"
    ports:
      - "8004:8004"

  gateway:
    build: ./gateway
    volumes:
      - ./gateway:/app
    ports:
      - "8000:8000"
    depends_on:
      - collector
      - alert_service
      - dashboard_service
      - user_management
    environment:
      - SECRET_KEY=your_super_secret_key
      - ALGORITHM=HS256
    
  influxdb:
    image: influxdb:2.7
    container_name: moniflow-influxdb
    restart: always
    env_file:
      - .env
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUXDB_ADMIN_USER}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUXDB_ADMIN_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG=${INFLUXDB_ORG}
      - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUXDB_DB}
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUXDB_ADMIN_TOKEN}
    ports:
      - "8086:8086"
    volumes:
      - influxdb_data:/var/lib/influxdb2

volumes:
  mongo_data:
  influxdb_data: